window.BOURBON_DATA = {
  "inventory": [
    {
      "id": "BV-0001",
      "distillery": "Buffalo Trace",
      "brand": "Weller",
      "expression": "Single Barrel",
      "release": "Gold",
      "proof": 97.0,
      "age": null,
      "mashBill": "Wheated",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Hidden",
      "msrp": 59.99,
      "notes": ""
    },
    {
      "id": "BV-0002",
      "distillery": "Buffalo Trace",
      "brand": "Weller",
      "expression": "Antique 107",
      "release": "Red",
      "proof": 107.0,
      "age": null,
      "mashBill": "Wheated",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Left Bottom",
      "msrp": 59.99,
      "notes": ""
    },
    {
      "id": "BV-0003",
      "distillery": "Buffalo Trace",
      "brand": "Weller",
      "expression": "Full Proof",
      "release": "Blue",
      "proof": 114.0,
      "age": null,
      "mashBill": "Wheated",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Left Bottom",
      "msrp": 66.99,
      "notes": ""
    },
    {
      "id": "BV-0004",
      "distillery": "Buffalo Trace",
      "brand": "Weller",
      "expression": "Special Reserve",
      "release": "Green",
      "proof": 90.0,
      "age": null,
      "mashBill": "Wheated",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Left Bottom",
      "msrp": 49.99,
      "notes": ""
    },
    {
      "id": "BV-0005",
      "distillery": "Buffalo Trace",
      "brand": "Eagle Rare",
      "expression": "10 Year",
      "release": "Silver Top",
      "proof": 90.0,
      "age": 10,
      "mashBill": "Low Rye",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Center Bottom",
      "msrp": 44.99,
      "notes": ""
    },
    {
      "id": "BV-0006",
      "distillery": "Buffalo Trace",
      "brand": "E.H. Taylor",
      "expression": "Small Batch",
      "release": "Red",
      "proof": 100.0,
      "age": null,
      "mashBill": "Bottled-in-Bond",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Center Bottom",
      "msrp": 59.99,
      "notes": ""
    },
    {
      "id": "BV-0007",
      "distillery": "Buffalo Trace",
      "brand": "E.H. Taylor",
      "expression": "Barrel Proof",
      "release": "Green",
      "proof": 127.3,
      "age": null,
      "mashBill": "Low Rye",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Right Bottom",
      "msrp": 84.99,
      "notes": ""
    },
    {
      "id": "BV-0008",
      "distillery": "Four Roses",
      "brand": "Four Roses",
      "expression": "Small Batch",
      "release": "Small Batch",
      "proof": 90.0,
      "age": null,
      "mashBill": "Four Grain",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Right Bottom",
      "msrp": 36.99,
      "notes": ""
    },
    {
      "id": "BV-0009",
      "distillery": "Grain & Barrel",
      "brand": "Chicken Cock",
      "expression": "KSB",
      "release": "KSB",
      "proof": 90.0,
      "age": null,
      "mashBill": "High Rye",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Right Bottom",
      "msrp": 54.99,
      "notes": ""
    },
    {
      "id": "BV-0010",
      "distillery": "Traverse City",
      "brand": "Traverse City",
      "expression": "Barrel Proof",
      "release": "Single Barrel",
      "proof": 108.0,
      "age": null,
      "mashBill": "High Rye",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Left Bottom",
      "msrp": 69.99,
      "notes": ""
    },
    {
      "id": "BV-0011",
      "distillery": "Traverse City",
      "brand": "Traverse City",
      "expression": "Small Batch",
      "release": "North Coast Rye",
      "proof": 90.0,
      "age": null,
      "mashBill": "High Rye",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Left Bottom",
      "msrp": 39.99,
      "notes": ""
    },
    {
      "id": "BV-0012",
      "distillery": "Traverse City",
      "brand": "Traverse City",
      "expression": "Limited Edition",
      "release": "Lakeside Peach",
      "proof": 70.0,
      "age": null,
      "mashBill": "Unknown",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Left Bottom",
      "msrp": 36.0,
      "notes": ""
    },
    {
      "id": "BV-0013",
      "distillery": "Old Fitzgerald",
      "brand": "Larceny",
      "expression": "Barrel Proof",
      "release": "B525",
      "proof": 117.4,
      "age": null,
      "mashBill": "Wheated",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Center Bottom",
      "msrp": 59.99,
      "notes": ""
    },
    {
      "id": "BV-0014",
      "distillery": "Diageo",
      "brand": "Bulleit",
      "expression": "12 Year",
      "release": "95 Rye",
      "proof": 92.0,
      "age": 12,
      "mashBill": "High Rye",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Center Bottom",
      "msrp": 54.99,
      "notes": ""
    },
    {
      "id": "BV-0015",
      "distillery": "Barton 1792",
      "brand": "Kirkland",
      "expression": "Bottled in Bond",
      "release": "KSB",
      "proof": 100.0,
      "age": null,
      "mashBill": "Bottled-in-Bond",
      "size": "750 ml",
      "status": "Opened",
      "fill": 0.75,
      "shelf": "Right Bottom",
      "msrp": 25.0,
      "notes": ""
    },
    {
      "id": "BV-0016",
      "distillery": "Buffalo Trace",
      "brand": "Buffalo Trace",
      "expression": "KSB",
      "release": "KSB",
      "proof": 90.0,
      "age": null,
      "mashBill": "Low Rye",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Right Bottom",
      "msrp": 27.0,
      "notes": ""
    },
    {
      "id": "BV-0017",
      "distillery": "Dynasty Spirits",
      "brand": "Trader Joe’s",
      "expression": "Tennessee Bourbon",
      "release": "Sour Mash",
      "proof": 80.0,
      "age": null,
      "mashBill": "Unknown",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Top Left",
      "msrp": 14.99,
      "notes": ""
    },
    {
      "id": "BV-0018",
      "distillery": "Bourbon Square",
      "brand": "Trader Joe’s",
      "expression": "KSB",
      "release": "KSB",
      "proof": 90.0,
      "age": null,
      "mashBill": "Unknown",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Center Bottom",
      "msrp": 14.99,
      "notes": ""
    },
    {
      "id": "BV-0019",
      "distillery": "A. Smith Bowman",
      "brand": "Isaac Bowman",
      "expression": "Small Batch",
      "release": "Port Barrel",
      "proof": 92.0,
      "age": null,
      "mashBill": "Unknown",
      "size": "750 ml",
      "status": "Opened",
      "fill": 0.75,
      "shelf": "Right Bottom",
      "msrp": 43.99,
      "notes": ""
    },
    {
      "id": "BV-0020",
      "distillery": "Pursuit",
      "brand": "Pursuit United",
      "expression": "Oak Collection",
      "release": "Blended",
      "proof": 108.0,
      "age": null,
      "mashBill": "Unknown",
      "size": "750 ml",
      "status": "Opened",
      "fill": 0.5,
      "shelf": "Right Bottom",
      "msrp": 74.99,
      "notes": ""
    },
    {
      "id": "BV-0021",
      "distillery": "Buffalo Trace",
      "brand": "Blanton’s",
      "expression": "Single Barrel",
      "release": "Single Barrel",
      "proof": 93.0,
      "age": null,
      "mashBill": "High Rye",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Display Shelf",
      "msrp": 74.99,
      "notes": ""
    },
    {
      "id": "BV-0022",
      "distillery": "Woodford Reserve",
      "brand": "Woodford Reserve",
      "expression": "Double Oaked",
      "release": "Double Oaked",
      "proof": 90.0,
      "age": null,
      "mashBill": "Low Rye",
      "size": "750 ml",
      "status": "Unopened",
      "fill": 1.0,
      "shelf": "Display Shelf",
      "msrp": 79.99,
      "notes": ""
    }
  ],
  "wishlist": [
    {
      "id": "WISH-0001",
      "distillery": "Buffalo Trace",
      "brand": "Weller",
      "expression": "CYPB",
      "priority": "High",
      "msrp": 64.99,
      "maxPrice": 150.0,
      "status": "Searching",
      "duplicateCheck": "Safe to Buy",
      "notes": ""
    },
    {
      "id": "WISH-0002",
      "distillery": "Buffalo Trace",
      "brand": "Weller",
      "expression": "12 Year Black Label",
      "priority": "High",
      "msrp": 49.99,
      "maxPrice": 150.0,
      "status": "Searching",
      "duplicateCheck": "Safe to Buy",
      "notes": ""
    },
    {
      "id": "WISH-0003",
      "distillery": "Buffalo Trace",
      "brand": "E.H. Taylor",
      "expression": "Single Barrel",
      "priority": "High",
      "msrp": 79.99,
      "maxPrice": 79.99,
      "status": "Searching",
      "duplicateCheck": "Safe to Buy",
      "notes": ""
    },
    {
      "id": "WISH-0004",
      "distillery": "Buffalo Trace",
      "brand": "E.H. Taylor",
      "expression": "Barrel Select",
      "priority": "High",
      "msrp": 81.99,
      "maxPrice": 81.99,
      "status": "Searching",
      "duplicateCheck": "Safe to Buy",
      "notes": ""
    },
    {
      "id": "WISH-0005",
      "distillery": "Buffalo Trace",
      "brand": "E.H. Taylor",
      "expression": "Straight Rye",
      "priority": "High",
      "msrp": 79.99,
      "maxPrice": 79.99,
      "status": "Searching",
      "duplicateCheck": "Safe to Buy",
      "notes": ""
    },
    {
      "id": "WISH-0006",
      "distillery": "Buffalo Trace",
      "brand": "E.H. Taylor",
      "expression": "Straight Rye Barrel Proof",
      "priority": "High",
      "msrp": 89.99,
      "maxPrice": 89.99,
      "status": "Searching",
      "duplicateCheck": "Safe to Buy",
      "notes": ""
    }
  ]
};
